name: Build and Process
# build and tweet
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Processing
      run: |-
        python 'python/processing.py'
        cat README.md
    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "index-updater-bot@example.com"
        git config --global user.name "index-updater-bot"
        git diff --quiet || (git add index.html && git commit -m "Updated index.html")
        git push
